[servers.sample]
bind = "localhost:8080"
protocol = "tcp" 
balance = "roundrobin"

max_connections = 10000
client_idle_timeout = "10m"
backend_idle_timeout = "10m"
backend_connection_timeout = "2s"

    [servers.sample.discovery]
    kind = "static"
    static_list = [
      "192.168.56.108:8080 weight=5",
      "192.168.56.109:8080 weight=5"
    ]

[servers.sample.healthcheck]
    fails = 1                      
    passes = 1
    interval = "2s"   
    timeout="1s"             
    kind = "ping"
    ping_timeout_duration = "500ms"